[package]
name = "rplay"
version = "0.1.0"
authors = ["Snow Pettersen <snowp@squareup.com>"]

[dependencies]
mio = "0.6"
protobuf = "2.0.4"
redis = "0.10.0"

[build]
build = "build.rs"

[build-dependencies]
protoc-rust = "2.5.0"

[[bin]]
name = "rplay"
path = "src/main.rs"
